### ISSUE TITLE
Running build script on Windows

### ISSUE THREAD

**Issue by AshNG2** [pavelloz/webpack-tailwindcss-purgecss#1]
I've had to make the following changes in the package.json scripts to run successfully on windows os:

    "build": "npm run clean && SET NODE_ENV=production& npx webpack-cli",
    "build:dev": "npm run clean && SET NODE_ENV=development& npx webpack-cli"

**Comment by pavelloz** [comment]
Ouh, thanks for letting me know.

Ill throw in cross-env asap ;)

**Comment by pavelloz** [comment]
Looks like it works correctly: https://github.com/pavelloz/webpack-tailwindcss-purgecss/runs/405030722

Cheers!
