### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by AshNG2** [pavelloz/webpack-tailwindcss-purgecss#2]
How are you handling multiple pages for anything besides src\index.html?

New pages in src\ are not transferred to app\assets which also means changes made in the src dir (for non index.html) isn't reflected in \app or on webpack dev server.

**Comment by pavelloz** [comment]
I dont handle them :)

If you can just replace index.html with `*` here and it should work.

https://github.com/pavelloz/webpack-tailwindcss-purgecss/blob/c986a53c1e669e3fb8931f36ef7d8e05f1da44b5/webpack.config.js#L54 

At least if i understand https://webpack.js.org/plugins/copy-webpack-plugin/ correctly.

**Comment by AshNG2** [comment]
Thanks I'll try this out tomorrow hopefully it'll work out for my needs.

Failing that I'll dive into the documentation you linked. 

Thanks again!

**Comment by AshNG2** [comment]
Through much trial and error, this is my working solution just in case anybody needs the same:
`new CopyPlugin([{ from: 'src/*.html', to: '[name].html' }]),
    new CopyPlugin([{ from: 'src/img', to: 'img', toType: 'dir' }]),`

Added last line for additional folder to copy across as well.

**Comment by pavelloz** [comment]
:)
